### ISSUE TITLE
Roadmap to 2.0.0

### ISSUE THREAD

**Issue by etagwerker** [DatabaseCleaner/database_cleaner#307]
Hey @DatabaseCleaner/owners 

First of all I wanted to thank all the contributors for their amazing work. 

Secondly, I wanted to start a discussion about `database_cleaner` version 2.0.0.

I can't find the discussion, but I'm _pretty sure_ @bmabey, other contributors and I talked about this in the past. 

What if we refactored `database_cleaner` into smaller gems? For example: `database_cleaner_active_record`, `database_cleaner_ohm`, `database_cleaner_redic`

They could all define their own ORM-specific logic and depend on `database_cleaner_core` for basic stuff (template methods, base classes, public interface to be implemented, etc.)

If you've used `omniauth` and `omniauth-<provider>` it's the same idea. 

What do you think? 

I think it'd be easier to maintain smaller gems that depend on each orm's gem. 

Feel free to comment here. 

Thanks!

Ernesto

PS: While we are at it, we could rename it to use `-` instead of `_` (but this is not that important)

**Comment by gurix** [comment]
I like the idea of seperating gems into multipe pieces because ....
* if you use multiple ORM's and don't want to clean all, you have to be carefull now. Seperating could so help avoid to clean accidently a legacy system.
* The releases for different ORM's could be faster. i.e, 1.4 is broken for mongoid just because a small typo, it's fixed on github but there is no hotfix 1.4.1. With dedicated gems, one could easy release the hofix without bothering others.

So a :+1: for seperating different ORMs in different gems.

**Comment by botandrose** [comment]
@etagwerker Closing this, since the gems were split out in v1.8, which I believe satisfies this issue.
