### ISSUE TITLE
column "table_rows" does not exist

### ISSUE THREAD

**Issue by coorasse** [DatabaseCleaner/database_cleaner#345]
Just use database_cleaner with Postgres and `DatabaseCleaner.strategy = :deletion`.
Version 1.4.1 is affected, version 1.4.0 I don't know. Version 1.3.0 is working fine.

**Comment by ryanong** [comment]
This happens to us also. I think it may have something to do with the way schema_plus interacts with database_cleaner

**Comment by coorasse** [comment]
No scherma plus for me.

**Comment by casiodk** [comment]
+1

**Comment by csdaraujo** [comment]
+1

**Comment by mcclymont** [comment]
+1 With Postgres. Also have pg, postgres_ext, schema_plus gems. I get the issue on 1.4.1 and 1.4.0. We had upgraded to 1.4.1 as part of a Rails 3 -> 4 upgrade. I downgraded database_cleaner to 1.3.0 and this error went away.

**Comment by shosti** [comment]
Also getting this. I'm not familiar with the inner workings of database_cleaner, but it looks like the problem is https://github.com/DatabaseCleaner/database_cleaner/blob/master/lib/database_cleaner/active_record/deletion.rb#L57 (introduced by https://github.com/DatabaseCleaner/database_cleaner/commit/81ca46565cf68a0e08fbfda7fb3542a119a2045d). `table_rows` doesn't exist in the Postgres information_schema AFAIK.

**Comment by shosti** [comment]
Actually looks like this is to do with SchemaPlus (+ maybe other similar gems). From a rails app using PG:

```
[3] pry(main)> ActiveRecord::ConnectionAdapters::Mysql2Adapter
=> SchemaPlus::ForeignKeys::ActiveRecord::ConnectionAdapters::Mysql2Adapter
```

That's triggering the `defined?` condition. I'd be happy to look into this some more...
