### ISSUE TITLE
Specifying location of database.yml

### ISSUE THREAD

**Issue by kristianmandrup** [DatabaseCleaner/database_cleaner#35]
Hi, 
Is there an easy way I can configure database_cleaner to load the database.yml from a different location than the default config/database.yml ?
Would really appreciate that!
Thanks

**Comment by kohrVid** [comment]
Not sure if anyone's run into this issue lately. I've found that the solution above doesn't work with the [standalone_migrations gem](https://github.com/thuss/standalone-migrations) for some reason and still returned an `ActiveRecord::ConnectionNotEstablished` error. As this is quite an old issue, I suppose the gem has changed substantially since that post was written.
Adding the following to `spec_helper.rb` seems to work at the moment:

    require 'yaml'
    RSpec.configure do |config|
      config.before(:suite) do
        // Read the database configuration for the test environment from the specified YAML file
        db = YAML.load(File.read("#{Dir.pwd}/path/to/config.yml"))["test"]
        
        // Establish a connection to the database using these settings
        ActiveRecord::Base.establish_connection(db)
        ...
      end
    end

Hope that helps if anyone else gets stuck.
