### ISSUE TITLE
1.8.0 base gem release has adapters in it

### ISSUE THREAD

**Issue by abrom** [DatabaseCleaner/database_cleaner#621]
Hi there,

Not sure if this may have been intentional or possibly a transitional step to a 2.0 release, but it looks like the 1.8.0+ gem cut has the split out ORM adapters included in it. Caused by:

https://github.com/DatabaseCleaner/database_cleaner/pull/560/files#diff-657fa18700ecf959b7fba9b0de545da0R29

See https://diff.coditsu.io/gems/database_cleaner/1.7.0/1.8.0#d2h-173909

I don't see any references in the base gem that would facilitate loading of the ORM gem code so it seems like it may have been an oversight?

Great gem btw, thanks 👍

**Comment by botandrose** [comment]
Hi @abrom! Thanks for writing, and for your interest in database_cleaner internals!

The inclusion is indeed intentional, and the base gem does indeed load the adapter code, here:

https://github.com/DatabaseCleaner/database_cleaner/pull/560/files#diff-8cb3a37f7659171d75ff6bdb7b47dd28R173

It's set up this unorthodox way to facilitate transition from 1.x to 2.x, as you guessed. By adding the adapters into the `$LOAD_PATH` only as need when they are autodetected, we can differentiate between adapters loaded in this manner, and adapters explicitly loaded by an adapter gem, e.g. database_cleaner-active_record, and deprecate the former.
