### ISSUE TITLE
0.0.0.0 doesn't count as a local host

### ISSUE THREAD

**Issue by joemsak** [DatabaseCleaner/database_cleaner#698]
Hello,

I'm setting up our rails app in Semaphore CI for the first time today and the default settings out of the box for a Rails workflow includes a postgres install and DATABASE_URL where the host is "0.0.0.0"

This fails Database Cleaner's safeguards with:

```
DatabaseCleaner::Safeguard::Error::RemoteDatabaseUrl:
ENV['DATABASE_URL'] is set to a remote URL. Please refer to https://github.com/DatabaseCleaner/database_cleaner#safeguards
``` 

Where the docs say that the host has to be one of: "localhost, .local or 127.0.0.1" - any reason why 0.0.0.0 isn't included?

For now I can change the semaphore ENV var to use "localhost" but it would have been nice for their default 0.0.0.0 to have been okay with this gem, if there is no particular reason not to include it. 

However, I'm happy to find out if there is something I am not understanding, please let me know, and thank you for this wonderful gem that has served me for nearly 15 years!

**Comment by etagwerker** [comment]
@joemsak Hi, thanks for submitting this issue! I think this was not considered because most of the people using this gem would probably use `localhost` or `127.0.0.1` so this sounds like an edge case.

I see that sometimes `0.0.0.0` is used to refer to "this host": 

- https://www.rfc-editor.org/rfc/rfc5735#section-3
- https://unix.stackexchange.com/questions/419880/connecting-to-ip-0-0-0-0-succeeds-how-why

So I would be open to a PR that adds a new value to this constant: https://github.com/DatabaseCleaner/database_cleaner/blob/main/lib/database_cleaner/safeguard.rb#L42 👍🏼

**Comment by joemsak** [comment]
Thank you so much @etagwerker - I've got advice from a coworker, someone with pretty deep technical knowledge, he says using "0.0.0.0" is "iffy" and "platform dependent" and he "hates" when it's used. So I think for now the recommended approach is to change OOB defaults, such as this one from Semaphore CI, to match what is already accepted by the gem.

Hopefully this PR at least helps in a search for the next person (-:
